# Generated by Django 4.0.3 on 2022-04-22 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0003_alter_funcionario_empresa'),
        ('documentos', '0003_documentos_arquivo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Documentos',
            new_name='Documento',
        ),
    ]
